- name: Stop timesyncd
  systemd:
    name: systemd-timesyncd.service
    state: stopped

- name: set timezone
  shell: timedatectl set-timezone Europe/London

- name: Copy over the timesyncd config
  template: src=../templates/timesyncd.conf dest=/etc/systemd/timesyncd.conf

- name: Start timesyncd
  systemd:
    name: systemd-timesyncd.service
    state: started
