- name: Apt Update and Upgrade
  apt:
    update_cache: 'yes'
    upgrade: 'yes'

- name: Auto remove unused packages
  apt:
    autoremove: 'yes'
    purge: 'yes'

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Rebooting machine
  reboot:
  when: reboot_required_file.stat.exists
